
 -- INSERT STATEMENTS

 -- Logins
 INSERT INTO LOGIN (EMAIL_ADDRESS, L_PASSWORD) VALUES ('darragh@grealish.com', 'drinkingshoes');
 INSERT INTO LOGIN (EMAIL_ADDRESS, L_PASSWORD) VALUES ('john@foley.com','drinkinggloves');
 INSERT INTO LOGIN (EMAIL_ADDRESS, L_PASSWORD) VALUES ('adam@byrne.com','drinkingsocks');
 INSERT INTO LOGIN (EMAIL_ADDRESS, L_PASSWORD) VALUES ('daniel@kennedy.com', 'drinkingpants');

 -- Departments
 INSERT INTO DEPARTMENT (D_NAME) VALUES ('Cappa');
 INSERT INTO DEPARTMENT (D_NAME) VALUES ('Monaleen');
 INSERT INTO DEPARTMENT (D_NAME) VALUES ('Brookfield');

 -- Jobs
 INSERT INTO JOB (TITLE) VALUES ('Manager');
 INSERT INTO JOB (TITLE) VALUES ('Engineer');
 INSERT INTO JOB (TITLE) VALUES ('Sales Rep');

 -- Companies
 INSERT INTO COMPANY (C_NAME) VALUES ('Lockheed Martin');
 INSERT INTO COMPANY (C_NAME) VALUES ('Boeing');
 INSERT INTO COMPANY (C_NAME) VALUES ('Raytheon');
 INSERT INTO COMPANY (C_NAME) VALUES ('Apple');
 INSERT INTO COMPANY (C_NAME) VALUES ('Microsoft');

 -- Employees
 INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, DOB, JOB_ID, DEPT_ID, LOGIN_ID) VALUES ('Darragh', 'Grealish', '04-JUN-03', 1, 2, 1);
 INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, DOB, JOB_ID, DEPT_ID, LOGIN_ID) VALUES ('John', 'Foley', '21-MAY-03', 2, 2, 2);
 INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, DOB, JOB_ID, DEPT_ID, LOGIN_ID) VALUES ('Adam', 'Byrne', '12-AUG-02', 2, 3, 3);
 INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, DOB, JOB_ID, DEPT_ID, LOGIN_ID) VALUES ('Daniel', 'Kennedy', '1-MAR-23', 3, 1, 4);

 -- Coordinators
 INSERT INTO COORDINATOR (EMPLOYEE_ID) VALUES (6);
 INSERT INTO COORDINATOR (EMPLOYEE_ID) VALUES (7);
 INSERT INTO COORDINATOR (EMPLOYEE_ID) VALUES (8);

 -- Assets
 INSERT INTO ASSET (A_NAME, BRAND, COMPANY_ID, A_MODEL) VALUES ('Laptop', 'Dell', 5, 'Latitude 5480');
 INSERT INTO ASSET (A_NAME, BRAND, COMPANY_ID, A_MODEL) VALUES ('Laptop', 'Dell', 5, 'Latitude 5480');
 INSERT INTO ASSET (A_NAME, BRAND, COMPANY_ID, A_MODEL) VALUES ('Laptop', 'Apple', 4, 'SmackBook Low');
 INSERT INTO ASSET (A_NAME, BRAND, COMPANY_ID, A_MODEL) VALUES ('Laptop', 'Apple', 4, 'SmackBook Low');

 -- Requests
 INSERT INTO REQUEST (EMPLOYEE_ID, ASSET_ID) VALUES (6, 1);
 INSERT INTO REQUEST (EMPLOYEE_ID, ASSET_ID) VALUES (9, 2);

 -- Assignments
 INSERT INTO ASSET_HISTORY (ASSET_ID, EMPLOYEE_ID, REQUEST_ID) VALUES (1, 6, 1);
 INSERT INTO ASSET_HISTORY (ASSET_ID, EMPLOYEE_ID, REQUEST_ID) VALUES (2, 9, 2);